
def log_exception(classname, function_name, exception_detail):
    print(" Exception occurred - In {0} class, inside function {1}, details are \n{2}\n".format(classname, function_name, exception_detail ))

def log_details(classname, function_name, output):
    print(" Details - In {0} class, inside function {1}, details are - \n{2}\n".format(classname, function_name, output ))